F95=gfortran

FFLAGS=-fdefault-real-8 -fbounds-check
#FFLAGS = -freal-4-real-16 -fbounds-check

#LIBS=-L/lib -L/usr/lib -L../Lib -lnetcdff -lslatec  -lhdf5_hl -lhdf5 -lz -lm
LIBS=-L/lib -L/usr/lib -L../Lib -lnetcdff
INCLUDES = -I/usr/include

all : $(SOURCE)
	$(F95) $(FFLAGS) $(INCLUDES) $(SOURCE) -o $(PROGRAM) $(LIBS)
