F95=ifort

FFLAGS=-g -d4 -r8 -CB

LIBS=-L/opt/netcdf-3.6.2/lib -L/opt/slatec -lnetcdf -lslatec
INCLUDES = -I/opt/netcdf-3.6.2/include

all : $(SOURCE)
	$(F95) $(FFLAGS) $(INCLUDES) $(SOURCE) -o $(PROGRAM) $(LIBS)
 

